### ISSUE TITLE
Missing pdbTlsKey, pdbTlsCrt, pdbTlsCat, WebServerUser, WebServerPwd and cdbNamespace keys in create-pdbdb.yaml

### ISSUE THREAD

**Issue by rbaumgar** [oracle/oracle-database-operator#125]
When creating CDB custom resource using sample create-pdb.yaml file (https://github.com/oracle/oracle-database-operator/blob/main/docs/multitenant/provisioning/create_pdb.yaml), request fails with:

```
$ kubectl apply -f create_pdb.yaml
The PDB "pdb1" is invalid: 
* spec.pdbTlsKey: Required value: Please specify PDB Tls Key(secret)
* spec.pdbTlsCrt: Required value: Please specify PDB Tls Certificate(secret)
* spec.pdbTlsCat: Required value: Please specify PDB Tls Certificate Authority(secret)
* spec.WebServerUser: Required value: Please specify the http webServerUser
* spec.webServerPwd: Required value: Please specify the http webserverPassword
```
The issue can be fixed by adding following to specs: section file:
spec:
```
...
  cdbNamespace: oracle  
  pdbTlsKey:
    secret:
      key: tls.key
      secretName: db-tls
  pdbTlsCrt:
    secret:
      key: tls.crt
      secretName: db-tls
  pdbTlsCat:
    secret:
      key: ca.crt
      secretName: db-ca 
  webServerUser:
    secret:
      key: webserver_user
      secretName: cdb1-secret
  webServerPwd:
    secret:
      key: webserver_pwd
      secretName: cdb1-secret  
...
```
