### ISSUE TITLE
OrdsSrvs secret vs password

### ISSUE THREAD

**Issue by gotsysdba** [oracle/oracle-database-operator#181]
Mismatch between CustomResourceDefinition ordssrvs.database.oracle.com and other code/documentation.

CRD defines:
```yaml
poolSettings:
 - db.secret:
   db.adminUser.secret
   db.cdb.adminUser.secret
```

Below code references db.password, db.adminUser.password, db.cdb.adminUser.password:
- apis/database/v4 
- commons/database/constants.go
- ords/ords_init.sh
- ords/runOrdsSSL.sh

Documentation is a mismatch.. some refer to .secret others to .password

===
I can fix this but what is the preference; *.secret or *.password?
