### ISSUE TITLE
Missing cdbTlsKey and cdbTlsCrt keys in cdb.yaml

### ISSUE THREAD

**Issue by styledigger** [oracle/oracle-database-operator#54]
When creating CDB custom resource using sample cdb.yaml file (https://github.com/oracle/oracle-database-operator/blob/main/config/samples/multitenant/cdb.yaml), request fails with:
```
$ kubectl apply -f cdb.yaml
The CDB "cdb-db21" is invalid: 
 * spec.cdbTlsKey: Required value: Please specify CDB Tls key(secret)
 * spec.cdbTlsCrt: Required value: Please specify CDB Tls Certificate(secret)
```
This is because `cdbTlsKey` and `cdbTlsCrt` keys are missing from cdb.yaml file. The issue can be fixed by adding following to `specs:` section of cdb.yaml file:
```
spec:
...
  cdbTlsKey:
    secret:
      secretName: "db-tls"
      key: "tls.key"
  cdbTlsCrt:
    secret:
      secretName: "db-tls"
      key: "tls.crt"
...
```
