### ISSUE TITLE
PDB delete/lifecycle

### ISSUE THREAD

**Issue by tenstad** [oracle/oracle-database-operator#84]
When deleting a PDB Kubernetes resource like the one below, I would expect the PDB to be deleted in the database. Would say that is the expected behaviour when working with Kubernetes. It also enables cleanup of ephemeral environments by deleting a namespace, without having to manually clean up all PDBs provisioned within it.

```yaml
apiVersion: database.oracle.com/v1alpha1
kind: PDB
spec:
  pdbName: pdb1
  action: Create
status:
  action: CREATE
  msg: Success
  phase: Ready
```

Here is the operator log from deleting pdb above:
```
2024-02-14T15:17:15Z INFO controllers.PDB Reconcile requested {"multitenantoperator": "oracle-database-operator-system/pdb1"}
2024-02-14T15:17:15Z INFO controllers.PDB PDB Resource Not found {"multitenantoperator": "oracle-database-operator-system/pdb1", "Name": ""}
```
and the state of the db after deleting the Kubernetes resource:
```
SELECT PDB_NAME FROM DBA_PDBS ORDER BY PDB_ID;
PDB_NAME
--------------------------------------------------------------------------------
PDB$SEED
PDB1
```

### action: Delete

Deleting a pdb by specifying `action: Delete` does not work, and results in the following:

```yaml
status:
  action: DELETE
  msg: >-
    ORA-65179: cannot keep datafiles for a pluggable database that is not
    unplugged

    ORA-06512: at line 3
  phase: Failed
```

EDIT: It does work when also having `dropAction: "INCLUDING"`.

### action: Unplug

It results in `Error "Required value: Please specify XML metadata filename" for field "spec.xmlFileName".` Adding `xmlFileName: foo.xml` seems to avoid the issue, resulting in the following status:

```yaml
status:
  msg: Waiting for PDB to be unplugged
  phase: Unplugging
```

When it succeeds unplugging, the operator also deletes the PDB resource, and the PDB is gone from the database.
